export const TeacherName = "Ratul Sarkar"
export const TeacherInfo = "Arth Hours - Dhara"
export const AttendanceKey = "Attendance"
export const DailyAttendanceKey = "Daily Attendance"
export const MarkAllPresentKey = "Mark all present"
export const DateFormat = "MMM DD, YYYY"
export const DateKey = "date"
export const AllStudentsKey = "All Students"